name: "Validate Phar"

on:
  workflow_dispatch:
  push:
    tags:
      - "**"

env:
  COMPOSER_VERSION: "^2.1"
  PHP_EXTENSIONS: "mbstring, ds"
  PHP_INI_VALUES: "memory_limit=-1, phar.readonly=0"

jobs:
  phar:
    name: "Validate Phar"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.4"

    env:
      COMPOSER_UNUSED_PHAR: "build/composer-unused.phar"
      COMPOSER_UNUSED_PHAR_SIGNATURE: "build/composer-unused.phar.asc"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@2.24.0"
        with:
          coverage: "none"
          tools: "composer:v2"
          extensions: "${{ env.PHP_EXTENSIONS }}"
          ini-values: "${{ env.PHP_INI_VALUES }}"
          php-version: "${{ matrix.php-version }}"

      - name: "Remove dev dependencies"
        run: "composer install --no-progress --no-dev --prefer-dist --optimize-autoloader"

      - name: "Validate configuration for humbug/box"
        run: ".phive/box validate box.json"

      - name: "Compile composer-unused.phar with humbug/box"
        run: ".phive/box compile --config=box.json --no-parallel"

      - name: "Show info about composer-unused.phar with humbug/box"
        run: ".phive/box info ${{ env.COMPOSER_UNUSED_PHAR }}"

      - name: "Validate composer-unused.phar against code"
        run: "php ${{ env.COMPOSER_UNUSED_PHAR }} --excludeDir=data"
